# tools/build_vowel_seed.py

from __future__ import annotations

import argparse
import json
from pathlib import Path

from config_loader.constraint_config_loader import (
    ConstraintConfigLoader,
)
from config_loader.optimization_config_loader import (
    OptimizationConfigLoader,
)
from evaluator.candidate_evaluator import CandidateEvaluator
from evaluator.candidate_scorer import CandidateScorer
from evaluator.character_analyzer import CharacterAnalyzer
from evaluator.constraint_factory import ConstraintFactory
from evaluator.corpus_analyzer import CorpusAnalyzer
from evaluator.finger_load_pipeline import FingerLoadPipeline
from evaluator.layout_evaluator import LayoutEvaluator
from models.corpus import Corpus
from models.corpus_entry import CorpusEntry
from models.layout import Layout
from optimizer.vowel_seed_builder import VowelSeedBuilder


def build_evaluator(
    optimization_config_path: Path,
    constraint_config_path: Path,
) -> CandidateEvaluator:
    optimization_config = OptimizationConfigLoader.load(
        optimization_config_path
    )

    constraint_config = ConstraintConfigLoader.load(
        constraint_config_path
    )

    return CandidateEvaluator(
        constraint_set=ConstraintFactory.create(
            constraint_config
        ),
        layout_evaluator=LayoutEvaluator(
            optimization_config.transition_cost_weights
        ),
        finger_load_pipeline=FingerLoadPipeline(),
        candidate_scorer=CandidateScorer(
            optimization_config.candidate_score_weights
        ),
        finger_load_budgets=(
            optimization_config.finger_load_budgets
        ),
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build-vowel-seed",
        description=(
            "Build the best valid vowel seed for a layout."
        ),
    )

    parser.add_argument(
        "layout",
        type=Path,
        help="Path to the input layout JSON file.",
    )

    parser.add_argument(
        "corpus",
        type=Path,
        help="Path to the UTF-8 corpus text file.",
    )

    parser.add_argument(
        "--config",
        type=Path,
        default=Path(
            "config/optimization/default.json"
        ),
        help=(
            "Path to the optimization configuration JSON file."
        ),
    )

    parser.add_argument(
        "--constraints",
        type=Path,
        required=True,
        help=(
            "Path to the constraint configuration JSON file."
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Optional output path for the generated "
            "seed layout JSON."
        ),
    )

    args = parser.parse_args()

    layout = Layout.load(
        args.layout
    )

    text = args.corpus.read_text(
        encoding="utf-8"
    )

    if not text.strip():
        raise ValueError(
            "corpus file must not be empty"
        )

    corpus = Corpus(
        entries=(
            CorpusEntry(
                text=text,
            ),
        ),
    )

    transition_statistics = CorpusAnalyzer().analyze(
        corpus
    )

    character_statistics = CharacterAnalyzer().analyze(
        corpus
    )

    constraint_config = ConstraintConfigLoader.load(
        args.constraints
    )

    if not constraint_config.vowel_position.enabled:
        raise ValueError(
            "vowel_position constraint must be enabled"
        )

    evaluator = build_evaluator(
        optimization_config_path=args.config,
        constraint_config_path=args.constraints,
    )

    builder = VowelSeedBuilder(
        evaluator=evaluator,
        allowed_positions=(
            constraint_config
            .vowel_position
            .allowed_positions
        ),
    )

    result = builder.build(
        layout=layout,
        transition_statistics=transition_statistics,
        character_statistics=character_statistics,
    )

    print("Best Vowel Seed")
    print("================")
    print()

    if result.score is None:
        print("Score: N/A")
    else:
        print(
            f"Score: {result.score:.6f}"
        )

    print()
    print("Vowel positions")
    print("---------------")

    for vowel in "AEIOU":
        print(
            f"{vowel}: "
            f"{result.layout.position(vowel)}"
        )

    if args.output is not None:
        output_data = {
            "name": (
                f"{result.layout.name} - Vowel Seed"
            ),
            "version": result.layout.version,
            "layer": result.layout.layer,
            "description": (
                "Best vowel seed generated by "
                "VowelSeedBuilder."
            ),
            "layout": dict(
                result.layout.items()
            ),
        }

        args.output.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        args.output.write_text(
            json.dumps(
                output_data,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print()
        print(
            f"Saved: {args.output}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())